packages:
    - apps/*
    - packages/*

catalog:
    "@biomejs/biome": 2.4.7
    "@types/node": ^25.5.0
    "@types/react": ^19.2.14
    "@usecannon/cli": ^2.26.0
    tsup: ^8.5.1
    typescript: ^5.9.3
    viem: ^2.47.4

onlyBuiltDependencies:
    - bufferutil
    - esbuild
    - keccak
    - protobufjs
    - utf-8-validate
