packages:
    - apps/*
    - packages/*
catalog:
    "@types/node": ^24.1.0
    "@types/react": ^19.1.8
    "@usecannon/cli": "^2.24.2"
    typescript: "^5.8.3"
    viem: ^2.33.1
onlyBuiltDependencies:
    - bufferutil
    - esbuild
    - keccak
    - protobufjs
    - utf-8-validate
