packages:
    - apps/*
    - packages/*

catalog:
    "@biomejs/biome": 2.3.8
    "@types/node": ^24.10.1
    "@types/react": ^19.2.7
    "@usecannon/cli": ^2.25.1
    tsup: ^8.5.1
    typescript: ^5.9.3
    viem: ^2.40.3

onlyBuiltDependencies:
    - bufferutil
    - esbuild
    - keccak
    - protobufjs
    - utf-8-validate
